/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package treehash

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
)

const (
	DEFAULT_CHUNK = 1024 * 1024
)

func ComputeHashFromFile(file string, offset, size, chunk_size int64) (string, string, error) {
	f, err := os.Open(file)
	if err != nil {
		return "", "", err
	}
	defer f.Close()

	if chunk_size == 0 {
		chunk_size = DEFAULT_CHUNK
	}

	fi, err := f.Stat()
	if err != nil {
		return "", "", err
	}
	if size == 0 {
		size = fi.Size() - offset
	}
	f.Seek(offset, os.SEEK_SET)

	buf := bufio.NewReader(f)

	h := sha256.New()
	t := New(int(chunk_size), sha256.New())
	mw := io.MultiWriter(h, t)
	io.CopyN(mw, buf, size)

	treeHash := hex.EncodeToString(t.Sum(nil))
	contentHash := hex.EncodeToString(h.Sum(nil))
	return contentHash, treeHash, nil
}
