/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package treehash

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"hash"

	"gitlab.com/NebulousLabs/merkletree"
)

type TreeHash struct {
	buf  *bytes.Buffer
	tree *merkletree.Tree
	hash hash.Hash

	segmentSize int
	cache       []byte
}

func New(segmentSize int, h hash.Hash) hash.Hash {
	return &TreeHash{
		buf:         bytes.NewBuffer(nil),
		tree:        merkletree.New(h),
		hash:        h,
		segmentSize: segmentSize,
		cache:       make([]byte, segmentSize),
	}
}

func (h *TreeHash) Write(p []byte) (n int, err error) {
	buf := h.buf
	tree := h.tree
	n, err = buf.Write(p)

	for {
		if buf.Len() >= h.segmentSize {
			buf.Read(h.cache)
			tree.Push(h.cache)
		} else {
			break
		}
	}
	return n, err
}

// Sum appends the current hash to b and returns the resulting slice.
// It does not change the underlying hash state.
func (h *TreeHash) Sum(b []byte) []byte {
	buf := h.buf
	tree := h.tree
	if buf.Len() > 0 {
		tree.Push(buf.Bytes())
	}
	return tree.Root()
}

// Sum appends the current hash to b and returns the resulting slice.
// It does not change the underlying hash state.
func (h *TreeHash) Reset() {
}

func (h *TreeHash) Size() int {
	return h.hash.Size()
}

func (h *TreeHash) BlockSize() int {
	return h.segmentSize
}

func ComputeHashFromList(list []string) string {
	h := merkletree.New(sha256.New())
	for i := 0; i < len(list); i++ {
		h.Push([]byte(list[i]))
	}
	return hex.EncodeToString(h.Root())
}
