/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobArchiveExportReq struct {
	// pull-from-cos
	Type string `json:"Type,omitempty"`
	Description string `json:"Description,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	Bucket string `json:"Bucket,omitempty"`
	Object string `json:"Object,omitempty"`
	Tier string `json:"Tier,omitempty"`
	Range string `json:"Range,omitempty"`
	Condition JobArchiveExportInfoCondition `json:"Condition,omitempty"`
}
