/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type JobOutputArchive struct {
	ArchiveId string `json:"ArchiveId,omitempty"`
	ArchiveDescription string `json:"ArchiveDescription,omitempty"`
	CreationDate time.Time `json:"CreationDate,omitempty"`
	Size int32 `json:"Size,omitempty"`
	SHA256TreeHash string `json:"SHA256TreeHash,omitempty"`
}
