/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VaultsSummary struct {
	Marker string `json:"Marker,omitempty"`
	VaultList []VaultInfo `json:"VaultList,omitempty"`
}
