/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestJoblistJSON(t *testing.T) {
	var job0 = &JobArchiveListSearchInfo{
		Action: "ArchiveRetrieval",
	}
	var job1 = &JobArchiveSearchInfo{
		Action:    "ArchiveRetrieval",
		ArchiveId: "1234",
	}
	var job2 = &JobArchiveImportInfo{
		Action: "PushToCOS",
	}
	var job3 = &JobArchiveExportInfo{
		Action: "PullFromCOS",
	}

	var list JobsList
	list.JobList = append(list.JobList,
		OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo{
			JobArchiveListSearchInfo: job0,
		},
		OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo{
			JobArchiveSearchInfo: job1,
		},
		OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo{
			JobArchiveImportInfo: job2,
		},
		OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo{
			JobArchiveExportInfo: job3,
		})
	txt, err := json.Marshal(list)
	assert.Nil(t, err)
	var newlist JobsList
	err = json.Unmarshal(txt, &newlist)
	assert.Nil(t, err)
	assert.Equal(t, len(newlist.JobList), int(4))
	assert.Equal(t, len(list.JobList), int(4))
	njob0 := newlist.JobList[0].JobArchiveListSearchInfo
	njob1 := newlist.JobList[1].JobArchiveSearchInfo
	njob2 := newlist.JobList[2].JobArchiveImportInfo
	njob3 := newlist.JobList[3].JobArchiveExportInfo
	assert.NotNil(t, njob0)
	assert.NotNil(t, njob1)
	assert.NotNil(t, njob2)
	assert.NotNil(t, njob3)
	assert.Equal(t, *job0, *njob0)
	assert.Equal(t, *job1, *njob1)
	assert.Equal(t, *job2, *njob2)
	assert.Equal(t, *job3, *njob3)
}
