/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobArchiveImportReq struct {
	// push-to-cos
	Type string `json:"Type,omitempty"`
	Description string `json:"Description,omitempty"`
	ArchiveId string `json:"ArchiveId,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	RetrievalByteRange string `json:"RetrievalByteRange,omitempty"`
	Bucket string `json:"Bucket,omitempty"`
	Object string `json:"Object,omitempty"`
	Tier string `json:"Tier,omitempty"`
}
