/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.4.3-3.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorMessage struct {
	// 错误码
	Code string `json:"code,omitempty"`
	// 错误信息
	Message string `json:"message,omitempty"`
	// 类型
	Type string `json:"type,omitempty"`
}
