/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type JobArchiveListSearchInfo struct {
	Action string `json:"Action,omitempty"`
	JobId string `json:"JobId,omitempty"`
	JobDescription string `json:"JobDescription,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	CreationDate time.Time `json:"CreationDate,omitempty"`
	CompletionDate time.Time `json:"CompletionDate,omitempty"`
	Completed bool `json:"Completed,omitempty"`
	StatusCode string `json:"StatusCode,omitempty"`
	StatusMessage string `json:"StatusMessage,omitempty"`
	VaultQCS string `json:"VaultQCS,omitempty"`
	InventorySizeInBytes string `json:"InventorySizeInBytes,omitempty"`
	InventoryRetrievalParameters JobInventoryRetrievalParameters `json:"InventoryRetrievalParameters,omitempty"`
}
