/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobArchiveExportInfoCondition struct {
	IfModifiedSince string `json:"If-Modified-Since,omitempty"`
	IfUmodifiedSince string `json:"If-Umodified-Since,omitempty"`
	IfMatch string `json:"If-Match,omitempty"`
	IfNoneMatch string `json:"If-None-Match,omitempty"`
}
