/*
 * Sample Access Code Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VaultInfo struct {
	CreationDate string `json:"CreationDate,omitempty"`
	LastInventoryDate string `json:"LastInventoryDate,omitempty"`
	NumberOfArchives int64 `json:"NumberOfArchives,omitempty"`
	SizeInBytes int64 `json:"SizeInBytes,omitempty"`
	VaultQCS string `json:"VaultQCS,omitempty"`
	VaultName string `json:"VaultName,omitempty"`
}
