/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// JobArchiveListSearchReq struct for JobArchiveListSearchReq
type JobArchiveListSearchReq struct {
	// archive-retrieval
	Type string `json:"Type,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	// 默认JSON
	Format string `json:"Format,omitempty"`
	Description string `json:"Description,omitempty"`
	InventoryRetrievalParameters JobInventoryRetrievalParameters `json:"InventoryRetrievalParameters,omitempty"`
}
