/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
import (
	"time"
)
// JobOutputArchive struct for JobOutputArchive
type JobOutputArchive struct {
	ArchiveId string `json:"ArchiveId,omitempty"`
	ArchiveDescription string `json:"ArchiveDescription,omitempty"`
	CreationDate time.Time `json:"CreationDate,omitempty"`
	Size int32 `json:"Size,omitempty"`
	SHA256TreeHash string `json:"SHA256TreeHash,omitempty"`
}
