/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// JobArchiveExportInfo struct for JobArchiveExportInfo
type JobArchiveExportInfo struct {
	Action string `json:"Action,omitempty"`
	JobId string `json:"JobId,omitempty"`
	JobDescription string `json:"JobDescription,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	CreationDate time.Time `json:"CreationDate,omitempty"`
	CompletionDate time.Time `json:"CompletionDate,omitempty"`
	Completed bool `json:"Completed,omitempty"`
	StatusCode string `json:"StatusCode,omitempty"`
	StatusMessage string `json:"StatusMessage,omitempty"`
	VaultQCS string `json:"VaultQCS,omitempty"`
	ArchiveId string `json:"ArchiveId,omitempty"`
	ArchiveSizeInBytes int64 `json:"ArchiveSizeInBytes,omitempty"`
	ArchiveSHA256TreeHash string `json:"ArchiveSHA256TreeHash,omitempty"`
	RetrievalByteRange string `json:"RetrievalByteRange,omitempty"`
	Bucket string `json:"Bucket,omitempty"`
	Object string `json:"Object,omitempty"`
	Condition JobArchiveExportInfoCondition `json:"Condition,omitempty"`
	ArchiveDescription string `json:"ArchiveDescription,omitempty"`
}
