/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VaultsSummary struct for VaultsSummary
type VaultsSummary struct {
	Marker string `json:"Marker,omitempty"`
	VaultList []VaultInfo `json:"VaultList,omitempty"`
}
