/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// PolicyCondition struct for PolicyCondition
type PolicyCondition struct {
	ConditionOperators map[string]interface{} `json:"ConditionOperators,omitempty"`
}
