/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// JobInventoryRetrievalParameters struct for JobInventoryRetrievalParameters
type JobInventoryRetrievalParameters struct {
	Format string `json:"Format,omitempty"`
	StartDate string `json:"StartDate,omitempty"`
	EndDate string `json:"EndDate,omitempty"`
	Limit string `json:"Limit,omitempty"`
	Marker string `json:"Marker,omitempty"`
}
