/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyStatePrincipal struct for PolicyStatePrincipal
type PolicyStatePrincipal struct {
	Qcs []string `json:"qcs,omitempty"`
}
