/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// PolicyState struct for PolicyState
type PolicyState struct {
	Effect string `json:"effect,omitempty"`
	Principal PolicyStatePrincipal `json:"principal,omitempty"`
}
