/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// NotificationConfiguration struct for NotificationConfiguration
type NotificationConfiguration struct {
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	Events []string `json:"Events,omitempty"`
}
