/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// ListPartsParts struct for ListPartsParts
type ListPartsParts struct {
	RangeInBytes string `json:"RangeInBytes,omitempty"`
	SHA256TreeHash string `json:"SHA256TreeHash,omitempty"`
}
