/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas
// JobArchiveExportReq struct for JobArchiveExportReq
type JobArchiveExportReq struct {
	// pull-from-cos
	Type string `json:"Type,omitempty"`
	Description string `json:"Description,omitempty"`
	CallBackUrl string `json:"CallBackUrl,omitempty"`
	Bucket string `json:"Bucket,omitempty"`
	Object string `json:"Object,omitempty"`
	Tier string `json:"Tier,omitempty"`
	Range string `json:"Range,omitempty"`
	Condition JobArchiveExportInfoCondition `json:"Condition,omitempty"`
}
