/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VaultInfo struct for VaultInfo
type VaultInfo struct {
	CreationDate string `json:"CreationDate,omitempty"`
	LastInventoryDate string `json:"LastInventoryDate,omitempty"`
	NumberOfArchives int64 `json:"NumberOfArchives,omitempty"`
	SizeInBytes int64 `json:"SizeInBytes,omitempty"`
	VaultQCS string `json:"VaultQCS,omitempty"`
	VaultName string `json:"VaultName,omitempty"`
}
