/*
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * Tecent Cloud Archive Storage Golang SDK.
 *
 * API version: 1.5.0
 * Contact: chennqqi@qq.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cas

import (
	"encoding/json"
	"fmt"

	"github.com/buger/jsonparser"
)

/*
	func UnmarshalJSON(txt []byte) error
	func MarshalJSON() ([]byte,error)
*/
type OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo struct {
	*JobArchiveListSearchInfo `json:"-"`
	*JobArchiveSearchInfo     `json:"-"`
	*JobArchiveExportInfo     `json:"-"`
	*JobArchiveImportInfo     `json:"-"`
	*JobArchiveInvetory       `json:"-"`
}

// JobsList struct for JobsList
type JobsList struct {
	JobList []OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo `json:"JobList,omitempty"`
	Marker  string                                                                                      `json:"Marker,omitempty"`
}

func (t OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo) MarshalJSON() ([]byte, error) {
	if t.JobArchiveListSearchInfo != nil {
		return json.Marshal(t.JobArchiveListSearchInfo)
	} else if t.JobArchiveSearchInfo != nil {
		return json.Marshal(t.JobArchiveSearchInfo)
	} else if t.JobArchiveExportInfo != nil {
		return json.Marshal(t.JobArchiveExportInfo)
	} else if t.JobArchiveImportInfo != nil {
		return json.Marshal(t.JobArchiveImportInfo)
	} else if t.JobArchiveInvetory != nil {
		return json.Marshal(t.JobArchiveInvetory)
	}
	return nil, nil
}

func (t *OneOfJobArchiveSearchInfoJobArchiveListSearchInfoJobArchiveImportInfoJobArchiveExportInfo) UnmarshalJSON(data []byte) error {
	action, _ := jsonparser.GetString(data, "Action")
	_, err := jsonparser.GetString(data, "ArchiveId")

	switch action {
	case "ArchiveRetrieval":
		if err == jsonparser.KeyPathNotFoundError {
			job := new(JobArchiveListSearchInfo)
			err := json.Unmarshal(data, job)
			if err != nil {
				return err
			}
			t.JobArchiveListSearchInfo = job
		} else {
			job := new(JobArchiveSearchInfo)
			err := json.Unmarshal(data, job)
			if err != nil {
				return err
			}
			t.JobArchiveSearchInfo = job
		}

	case "PushToCOS":
		job := new(JobArchiveImportInfo)
		err := json.Unmarshal(data, job)
		if err != nil {
			return err
		}
		t.JobArchiveImportInfo = job

	case "PullFromCOS":
		job := new(JobArchiveExportInfo)
		err := json.Unmarshal(data, job)
		if err != nil {
			return err
		}
		t.JobArchiveExportInfo = job

	case "InventoryRetrieval":
		job := new(JobArchiveInvetory)
		err := json.Unmarshal(data, job)
		if err != nil {
			return err
		}
		t.JobArchiveInvetory = job

	default:
		return fmt.Errorf("unknow action=[%v]", action)
	}
	return nil
}
